version: "3"

services:
  mongo_db:
    image: mongo
    container_name: currencies-exchange_mongo
    restart: unless-stopped
    hostname: currencies-exchange_mongo-host
    env_file:
      - .env
    networks:
      - server
    volumes:
      - ./mongodb:/data/db
    ports:
      - $MONGO_PORT:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DATABASE_NAME
networks:
  server:
    driver: bridge
volumes:
  data: